### PR TITLE
BitcoinZwalletUI update to v2.0.7-u2

### PR DESCRIPTION
**Pull request by MarcelusCH**
**Description**

This PR (version 2.0.7 update 1) adds some new functionality to the wallet.
The new features have been added in the "Address Panel Tab" as "right clic menu".

Wallet encryption as be re-activated. 
This is experimental and needs to add `developerencryptwallet=1` in the `bitcoinz.conf` file. 

This update also prepares for the next version 2.0.7-u2 that will be a complet BtcZ'ify of the wallet.
(See the btczify branche : https://github.com/MarcelusCH/bitcoinz-wallet/tree/btczify)

**New features**
- Added Address Message Signing
https://bitcoinz-dev-tools.github.io/BTCZ-RPC-DOC/signmessage.html
- Added Shield Coinbase 
https://bitcoinz-dev-tools.github.io/BTCZ-RPC-DOC/z_shieldcoinbase.html
- Added Merge To Address
https://bitcoinz-dev-tools.github.io/BTCZ-RPC-DOC/z_mergetoaddress.html

Note:
To use the "Merge To Address" function, `experimentalfeatures=1` and `zmergetoaddress=1` have to be added in the `bitcoinz.conf` file. Otherwise it will show an error box informing that.

### CODE REVIEW

**Comment by MarcelusCH** [comment]
About the wallet encryption, check also this: 
https://bitcoinz-dev-tools.github.io/BTCZ-RPC-DOC/encryptwallet.html

We have to add an WARNING box some where... 
Here my first remarks/concerns about wallet encryption:
- I not found any way to undo the wallet encryption ?!
- It seems that this poses security concerns :
https://zcash.readthedocs.io/en/latest/rtd_pages/security_warnings.html

**Comment by cryptorex** [comment]
Yeah, probably a warning box, or just in the features on releases we can let them know its up to them to encrypt the wallet at their own risk.

I don't see any RPC command that allows decryption so they would have to re-create their wallet I guess and import their keys to another wallet.dat for them to have an unencrypted wallet.

Good work on adding the new features!

> About the wallet encryption, check also this: https://bitcoinz-dev-tools.github.io/BTCZ-RPC-DOC/encryptwallet.html
> 
> We have to add an WARNING box some where... Here my first remarks/concerns about wallet encryption:
> 
>     * I not found any way to undo the wallet encryption ?!
> 
>     * It seems that this poses security concerns :
>       https://zcash.readthedocs.io/en/latest/rtd_pages/security_warnings.html

**Comment by MarcelusCH** [comment]
Better to let it disabled for now. So I comited the disabling of it.

I prepared the warning box in the new branch. 
And maybe we re-check for enable the wallet encryption next time.

**Just an input about Address Signing Message;** this could be used as system access (MFA) credentials ;-)
... Also I hop this will give some ideas to our smart members.

**Comment by cryptorex** [comment]
> Better to let it disabled for now. So I comited the disabling of it.
> 
> I prepared the warning box in the new branch. And maybe we re-check for enable the wallet encryption next time.
> 
> **Just an input about Address Signing Message;** this could be used as system access (MFA) credentials ;-) ... Also I hop this will give some ideas to our smart members.

ok @MarcelusCH i think it looks good to me, we can probably merge this?  interesting idea about MFA hmmmm

**Comment by MarcelusCH** [comment]
Changed mainClassSpace by : com.bitcoinz.btczui.
Added some info in the about dialog box.
Updated Readme and docs.

**Comment by MarcelusCH** [comment]
The PR #15 can also be closed.

**Pull request merged**
